srvrco/getssl

getssl

This lets getssl create the ACL directory if it does not exist. Or fail with a helpful message if it cannot be created.

create ACL directory if it does not exist

---

getssl

i added (grep -v '^$') to remove empty lines, and replace \n with a comma.
tested with ./getssl -c example.com to get
> SANS=www.example.org,example.edu,example.net,example.org,www.example.com,www.example.edu,www.example.net
instead of
> SANS=www.example.orgexample.eduexample.netexample.orgwww.example.comwww.example.eduwww.example.net

fix creating config for domains with more than 1 alternative name

---

getssl

it looks at ACL for ssh: and then tries to get it from RELOAD_CMD...
seems to me it should check for ssh: in the RELOAD_CMD
i switched a config to dns-challenge and then found it didn't reload apache on the server...

reload-cmd-fix

---

getssl

i was testing with the DNS-challenge yesterday and found that it would sometimes fail, this might be because of caching so i added a 60 second sleep to make sure the minimum TTL would be over.
also my DNS-provider has multiple hosts behind the same IP which don't sync at exactly the same time, so when requesting multiple times you could get a correct result and 5 seconds later get a wrong one.
with the extra 60 seconds this doesn't happen.
would you prefer if i change this to a config-variable? i personally don't mind the extra wait, since the DNS-challenge isn't the fastest way to go anyway...

extra-wait-for-dns

---

getssl

i found a couple of exits which were echo's with a graceful_exit, i changed these to error_exit

replace graceful_exit commands with error_exit after errors

---

getssl

i added a domain in my config, but when requesting the certificate it just used the old csr, and i got a domain without the newly added domain from the config.
the csr is now checked against the config, and the config against the csr,
when there is a difference between the csr and the config a new csr is generated.

better csr check, and recreate

---

getssl

for the DNS-challenge and for the webserver type it is needed that the DNS entry for the domain exists.
it is not strictly necessary to check this for all domains, but when a domain does not exists you'll get an error when trying to lookup the nameserver or when trying to reach the webserver.

do nslookup on each domain before starting requests

---

getssl

i was testing with a domain with 4 alternative names, and doing the DNS-challenge took around 20 minutes, since for every domain i have to wait until the DNS-server has updated my acme-challenge (120sec), and then wait and extra 60sec just to be sure.. after this change it takes about 3 minutes, and it doesn't matter that much if you have 1 or 10 alternative-names
i moved some code to a function (check_challenge_completion) and changed the flow to first run all DNS_ADD commands, then check the dns for all domains, wait an extra 60 seconds, and then run the check_challenge_completion for all domains.
i made an extra directory dns_verify in the TEMP_DIR to store the variables per domain

dns first add all domains, then check all

---

getssl

`rm` commands, if left unchecked can be dangerous, potentially destroying unintended parts of the filesystem.
* Protect `rm` commands from empty variables with `${foo:?}` which will produce an error if `$foo` is unset or null.
* Create TEMP_DIR with `mktemp`.

Defensively protect filesystem from rm commands with empty values

---

getssl

When parsing the JSON response from the HTTP request to create a new certificate... Use `grep -Po` instead of `egrep` as egrep is not matching across all the lines we need to match.
Also trim leading whitespace from `token` by passing it through `tr`.
Refs #35

Use grep -Po for parsing JSON response

---

getssl

Useful for shared webhosting services without proper ssh/sftp access using keys
requires sshpass

Add sftp with password to copy files

---

README.md

only users with write access can use ssh links to clone

update clone link

---

getssl

Not sure if this particular check suits you but it seems if the DNS_ADD_COMMAND fails there's no point looping 100 times to see if the entry is there.

Test return status of DNS_ADD_COMMAND

---

getssl

$WORKING_DIR should always be correct so always passing it along should be the most efficient way to make sure the original -w is respected, right?

Respect -w when using -a

---

README.md
create-getssl-config
getssl

i added the server types which are available in openssl s_client to getssl
this way you can check if the certificate has been installed correctly on more than just web and ldap servers
i will add some documentation in the next couple of days, but i wanted some feedback on the SERVER_TYPE naming.
i think for consistency it might be better to rename "webserver" to "https" (but keep "webserver" as fallback)

add more server-types based on openssl s_client

---

getssl

OPENSSL_CONF needs to be set otherwise the SSLCONF option has no effect on the execution of all the openssl commands.

Set OPENSSL_CONF

---

README.md

It's entirely my fault for killing a production site for 10 minutes while I figured this out, and for not making a backup of the working private key and certificate, but I think it would help people to emphasize that it uses the staging server by default.
Especially since changing the setting doesn't work unless you remove the old certificate from `~/.getssl/$domain` first, which took another few minutes to figure out. The script will not detect that the certificate is untrusted and goes "oh I'm all done already, it's still valid for a while".
(Other than that, 10/10! So much simpler and better than the default letsencrypt client, loved it.)

Emphasized "will use untrusted by default"

---

README.md
getssl

@srvrco please have a look. Additionally to fixing the issue I updated the README.md a little bit to have it match the current version.
Fixes #123.
The `-Q` switche now does the same like `-q` with the only difference that `-Q` additionally mutes the 
> Updated getssl from v1.XX to v1.XY
messages.

Add -Q switch to mute notification about successfull upgrades of getssl

---

.editorconfig

i found http://editorconfig.org/
this is a file which defines tabs/spaces and indentation for a project, a lot of IDE environments already support this, and are then automatically configured correctly for this project.
saves some time changing tabs to spaces etc.

feature add .editorconfig file

---

getssl

i found that when you add a new domain which has a wrong certificate installed, it wasn't detected.
since when there is no local certificate file the file is downloaded, and the domain check is therefore skipped, the next run the local file is only checked to see if it matches the remote version.
i changed the flow a bit so that the file is checked for the right domain before downloading

fix first download check

---

dns_scripts/dns_add_cloudflare
dns_scripts/dns_del_cloudflare

Reworked DNS Cloudflare scripts:
- removed dependency on external tools (grep, awk, sed), use only pure bash and curl
- allow set auth key from env
- do strict response json structure parsing
- don't query CF twice for the same thing
- add optional parameter to delete only selected ACME token (delete all as default - not changed)
- report errors returned from CF
Tested with:
- GNU bash, version 4.4.0(1)-release (i586-slackware-linux-gnu)
- GNU bash, version 4.3.42(1)-release (mipsel-openwrt-linux-gnu)
- GNU bash, version 4.1.5(1)-release (arm-unknown-linux-gnueabi)
- curl 7.50.3 (i686-pc-linux-gnu) libcurl/7.50.3 OpenSSL/1.0.2j zlib/1.2.8 libidn/1.33 libssh2/1.7.0
- curl 7.49.0 (mipsel-openwrt-linux-gnu) libcurl/7.49.0 OpenSSL/1.0.2h zlib/1.2.8
- curl 7.21.0 (arm-unknown-linux-gnueabi) …

Cloudflare

---

getssl

If someone is running load balanced servers that use the same certificate there is some time needed to wait until the token is replicated within the server instances.

add HTTP_TOKEN_CHECK_WAIT option (1.84)

---

getssl

In openssl FIPS mode, files don't have the "[RSA|EC] PRIVATE KEY" text inside when the private key is generated.
Therefore, grep will not find the words and fails with invalid key file.
Resolves: #204

check generated keys without depending on inside text

---

getssl

After each failed / successful upgrade of getssl, the temporary file /tmp/tmp.XXXXXXXXXX is not removed in all situations. Only when auto-upgrade is disabled or no update was found, the temporary file is removed. In all other code paths, the removal of the tempfile created earlier is never reached.

fix leftover tmpfiles in upgrade routine (1.94)

---

README.md
getssl

This PR adds an option to keep a limited amount of old versions on the filesystem when getssl is upgraded. You specify the amount of versions you want to keep with the -k option. For example, specifying:
`getssl -u -k 4`
will keep only 4 old versions in the same directory in which getssl is installed. Completely disabling old versions to keep can be done with:
`getssl -u -k 0`
Then, after each upgrade, the old version will be removed immediately. 
Not specifying the -k option means the old behaviour (keeping all versions) is in still place.

Added option to keep a limited amount of old versions when upgrading

---

Makefile

This adds a simple Makefile which can be used to install the software.
Currently there is only a single install target.

Add Makefile with install target

---

getssl

This implements a new variable OCSP_MUST_STAPLE which adds the OCSP Must-Staple detail to the SAN section of the CSR.
If the openssl version is >= 1.1.0, one can also use "tlsfeature = status_request".
See [this blog post](https://scotthelme.co.uk/ocsp-must-staple/) for more details.

Add OCSP Must-Staple

---

README.md

Hi there,
I recently used `getssl` and found it to be a pleasure: just as simple and straightforward to use as the official Acme client. While reading the README, I noticed some small issues with formatting and punctuation so I figured I'd submit this PR to help improve the documentation.
Best wishes,
Anthony

Minor formatting and punctuation fixes.

---

dns_scripts/dns_route53.py

| Q | A
| --- | ---
| Bug fix? | y
| New feature? | n
| BC breaks? | n
| Deprecations? | n
| Fixed tickets | fixes #398, 
| Related issues/PRs | #418
| License | GPL-3.0+
This adds a dot in front of the `fqdn` and the zone name, so the comparison will only check against full DNS parts of the `fqdn` and the zone name. This will prevent to match a `fqdn` against an unrelated zone name which overlaps with the wanted zone in the naming.

[Route53] Make a stricter comparison for matching against zone names

---

getssl

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fix #423, fix #427
| Related issues/PRs | -
| License | GPL3.0+
Sets curl to use `--http1.1` for newly HTTP2 activated ACME API
With HTTP2 response headers are all lowercase. This is a quickfix to get getssl working again, a follow up to support HTTP2 will be created.

Use HTTP 1.1 as workaround atm

---

getssl

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #425 
| Related issues/PRs | -
| License | GPL3.0+
Fixes the awk processing to get the redirect location to be case insensitive because of lowercased HTTP/2 headers.

Case insensitive processing of agreement url because of HTTP/2

---

getssl

LetsEncrypt v2 returns the certificate and ca-certificate already bundled into a single file.  As a quick fix this just splits it into the two files the rest of the code is expecting.

Fix missing chain.crt #349

---

getssl

Ref https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380

Fix #462 use POST-as-GET requests on ACMEv2 endpoints

---

getssl

acme-v02 API can return more than 1 URL inside a http-01 challenge object, this change just selects the first one which appears to always be the one we want.
Example of the problem here: https://gist.githubusercontent.com/2ZZ/74bd2cb3ad2bd4f7a578fa9077ac383d/raw/d342aac4c175f1ca1b04b0070839fffd739232ff/getssl-test.sh

Only select first URL returned from acme-v02

---

getssl

First a small fix related to #332 where the most recent versions of the bind nslookup is not accepting `-debug=1`
Second (related to #421) is a fix to allow json_awk to run on the majority of awk versions.
Tested on gawk-v4, gawk-v5, mawk-1.3.3, mawk-1.3.4, busybox-awk-1.30.1, original-awk-2012-12-20-6 as well as gawk not in a UTF-8 locale.
Example test file (20130418-issue-001-test.json from JSON.awk):
``` json
{"sh": "[ -r 'k.cfg' ] || echo \"# k.cfg - `date`\" >'k.cfg';s=$(awk \"`echo -n 'BEGIN{nf=1} /^@Bs*mode=/{sub(/=.*/,@Q=123@Q);nf=0} {print} END{if(nf) print @Qmode=123@Q}'|sed 's/@Q/\\x22/g;s/@B/\\x5C/g'`\" 'k.cfg') && [ 0 != ${#s} ] && echo -n \"$s\" >'k.cfg'"}
```
And many others in: https://github.com/nst/JSONTestSuite
For that list this change does pass a couple of extra …

Bugfixs for json_awk and nslookup

---

getssl

This is very minor, but the trailing slash of the Let's Encrypt staging server URL broke API discovery (client was trying https://acme-staging-v02.api.letsencrypt.org//directory, which results in a 403). The "Unknown API" error confused me quite a bit...

Fix domain template url

---

.github/workflows/run-all-tests.yml
.github/workflows/shellcheck.yml
getssl
test/11-test--install.bats
test/Dockerfile-alpine
test/Dockerfile-centos6
test/Dockerfile-centos7
test/Dockerfile-centos7-staging
test/Dockerfile-debian
test/Dockerfile-ubuntu
test/Dockerfile-ubuntu-staging
test/Dockerfile-ubuntu16
test/Dockerfile-ubuntu18
test/test-config/getssl-etc-template.cfg

Two basic improvement I usually patch every time I download last release. Hope others see useful.
Adding alternative working directories while keeping default behavior if no config file is found on them.
Adding -i|--install command to only install and reload service.

Improvements: alternative working dirs and -i|--install command

---

getssl

HAS_HOST and HAS_NSLOOKUP use "false" or "true", ie. they both are never empty so condition -n "$var" is true everytime, even if value is "false" while the command is missing

fix HAS_HOST and HAS_NSLOOKUP condition

---

getssl

The version number needs to come last, otherwise the rest of the getssl source file gets printed along with the actually wanted changelog lines when running `getssl -u`.

Fix changelog formatting

---

getssl

The dns query is often being reprinted as a comment as part of the drill/dig output
this caused multiple hits for the grep, making the comparison invalid.
Make sure we strip out comments before we look for the challenge text in the txt record.

bugfix: strip comments in drill/dig output when checking txt in dns.

---

dns_scripts/Cloudflare-README.md
dns_scripts/dns_add_cloudflare
dns_scripts/dns_del_cloudflare

Allows using scoped API Tokens for Cloudflare DNS validation instead of account level API Keys
- least privilege tokens with access to only modify the zone's DNS records
- adds a README

Allow scoped Cloudflare API Tokens

---

README.md

As `markdownlint` was mentioned here: https://github.com/srvrco/getssl/pull/601#pullrequestreview-537817573
Why not let us make markdownlint happier?
```
README.md:1 MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "![Run all tests](https://githu..."]
README.md:2 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "# getssl"]
```
I know it's not a very formal commit message, hope you won't mind, it's tribute to this Linux kernel commit: https://github.com/torvalds/linux/commit/690b0543a813b0ecfc51b0374c0ce6c8275435f0 :)

Make markdownlint happy about README.md

---

.editorconfig

Makefile is using tabs as indentation, not spaces.
Not only in this project, and also in many other places.

Correct Makefile indentation in .editorconfig

---

other_scripts/cpanel_cert_upload

It should be two spaces, not three or four here 😆

Fix indentation to two spaces in other_scripts/cpanel_cert_upload

---

getssl

A regexp to extract 'Subject Alternative Name' doesn't work when the domain use a minus character.
For grep regexp, to lose its special meaning inside brackets, the minus character must be placed in the first or last position in the list.
https://www.gnu.org/software/grep/manual/grep.html#Character-Classes-and-Bracket-Expressions
You can check:
```bash
echo -e 'X509v3 Subject Alternative Name:\n    DNS:a2-b2.net' | grep -Eo "DNS:[a-zA-Z 0-9.-\*]*"
echo -e 'X509v3 Subject Alternative Name:\n    DNS:a2-b2.net' | grep -Eo "DNS:[a-zA-Z 0-9.\*-]*"
```
To test:
Generate the configuration (`getssl -c`) for a domain that have an existing certificate whose subject alternative name use a domain containing a minus character.
I think the comment line can be deleted. I tested on CentOS 7. It seems to …

Wrong SANS when domain contains a minus character

---

getssl
test/u4-create-csr-and-ifs.bats

- use \n as delimiter for read to array
- use \n as delimiter for comparing SANs

Issue #614: Fix delimiter issues with ${alldomains[]} in create_csr()

---

getssl
test/31-test-posix-error.bats
test/32-test-upgrade.bats
test/test-config/getssl-http01.cfg

Running with `sh getssl` starts bash in posix mode, which causes a parse error from v2.31 onwards.  Running with `bash getssl` solves this issue.
Fixes #611

Show error if running in posix mode

---

getssl

Background:
* DAVS account has the `.well-known/acme-challenge` as its home directory
* For the DAVS account, the token needs thus to be uploaded to `https://my-server.com:1234/TOKEN`
* The current implementation expands the URL to `https://my-server.com:1234//TOKEN` (double slash)
* The double slash causes the upload of the token to fail.
Used sed for substitution for better readability.

Fix double slash when using root directory with DAVS

---

README.md
getssl

Use a bash array to set several commands. (Commands use the usual syntax.)
The current syntax is unchanged when setting a single command.
As it's possible to install a certificate in several locations, it may useful to be able to run several reload commands (even if it is not so common).
So, you can set a single command as usual:
``` bash
RELOAD_CMD="ssh:sshuserid@server5:systemctl reload httpd"
```
Or set several commands, like reload two servers:
``` bash
RELOAD_CMD=("ssh:sshuserid@server5:systemctl reload httpd" "ssh:sshuserid@server6:systemctl reload nginx")
```
Or log the renew:
``` bash
RELOAD_CMD=("ssh:sshuserid@server5:systemctl reload httpd" "logger getssl renew for server5 efficient.")
```

Add the ability to set several reload commands

---

dns_scripts/dns_add_godaddy
dns_scripts/dns_godaddy

Currently, GoDaddy's API requires a list as a body for adding a new record: [reference](https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName)
Also the API does not accept record names ending with the `.`. To achieve the same result as before it is enough to send just the name of the record without the domain appended to it.
The third change is changing the order of fields when comparing records fetched from GoDaddy. Maybe it would be enough to compare just the names as the ordering of the fields might change again? Or use JSON script to get the proper data. I'm not that familiar with bash scripts to implement that tough. 
@timkimber Please review

Update GoDaddy DNS scripts

---

getssl
test/18-retry-dns-add.bats

getssl fails to check DNS if `_acme-challenge.{domain}` is a CNAME to a domain hosted by another DNS server.  
This patch set should fix that, by resolving CNAMEs first and then searching the authoritative DNS server.
I suspect that it still won't work if `AUTH_DNS_SERVER` is set in the config, but I also don't see how this could be fixed.

WIP: Fix DNS challenges with CNAMEs on different DNS servers

---

getssl

This will ignore the [shellcheck check SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086), if we don't use arrays yet as suggested by the tool.

shellcheck disable=SC2086

---

getssl

When the debug option is used, it may be useful to see errors that may occured
on remote calls (ssh).

Do not redirect outputs on remote commands when the debug option is used

---

getssl

Some of the lines the heredoc's had leading spaces or spaces instead of tabs. Fix them so it's consistent.

Fix leading whitespace in heredoc so it's uniform

---

getssl

When PRIVATE_KEY_ALG is changed from rsa to one of the EC types (or vice versa) the key file needs to be deleted (regardless of value of REUSE_PRIVATE_KEY). Otherwise you still get a certificate of the old (previous) type.

delete key file when key alg has changed

---

getssl

When FULL_CHAIN_INCLUDE_ROOT is set, DOMAIN_CHAIN_LOCATION was sending just the intermediate and server cert. Copying $FULL_CHAIN instead of $CERT_FILE+$CA_CERT fixes this.

Fix DOMAIN_CHAIN_LOCATION to copy correct file

---

dns_scripts/dns_add_acmedns
dns_scripts/dns_del_acmedns
getssl

Notably:
* fix the script dns_del_acmedns
* Add the ability to set DNS API configuration at domain level
* Add the ability to choose the ACME-DNS server (for self-hosted servers)
ACME-DNS has an unusual usage comparing to other DNS providers: it provides credential for each registered domain and allow only to update its challenge.

Improve the dns scripts for ACME-DNS

---

README.md
dns_scripts/dns_add_windows_dns_server
dns_scripts/dns_del_windows_dns_server
getssl
other_scripts/iis_install_certeficate.ps1

Supporting two bashes `GIT` mingw64_nt and `Rtools4.0` msys_nt.
Enabled `CSR_SUBJECT ` for OS mingw64_nt.
Fixed `nslookup` to be used for both NT OSes mingw64_nt and msys_nt.
Enabled `CSR_SUBJECT  ` for OS mingw64_nt.
Added a dot after the domain in nslookup "${rr}`.`" (It must be set to avoid using search domains when querying the domain).

Windows and IIS Support. Windows bash support.

---

getssl

Changes the small misalignment in the help text line for `--account-id` option:
Before:
After:

Help text: Fix text algining for `--account-id` option

---

dns_scripts/dns_add_vultr
dns_scripts/dns_del_vultr

This PR will add Vultr DNS verification scripts to the repository. 
Scripts use methods provided by the Vultr API:
https://www.vultr.com/api/#tag/dns

Added Vultr DNS Scripts

---

dns_scripts/dns_add_del_aliyun.sh
dns_scripts/dns_add_dnspod
dns_scripts/dns_add_duckdns
dns_scripts/dns_add_godaddy
dns_scripts/dns_add_ionos
dns_scripts/dns_add_joker
dns_scripts/dns_add_linode
dns_scripts/dns_add_manual
dns_scripts/dns_add_nsupdate
dns_scripts/dns_add_ovh
dns_scripts/dns_add_pdns-mysql
dns_scripts/dns_add_windows_dns_server
dns_scripts/dns_del_dnspod
dns_scripts/dns_del_duckdns
dns_scripts/dns_del_godaddy
dns_scripts/dns_del_ionos
dns_scripts/dns_del_joker
dns_scripts/dns_del_linode
dns_scripts/dns_del_manual
dns_scripts/dns_del_nsupdate
dns_scripts/dns_del_ovh
dns_scripts/dns_del_pdns-mysql
dns_scripts/dns_del_windows_dns_server
dns_scripts/dns_godaddy
other_scripts/cpanel_cert_upload

Pretty much what it says on the tin -- most of the scripts use /usr/bin/env instead of directly calling /bin/bash, but a not-insignificant few don't, which breaks platforms that don't have bash in /bin (NetBSD, FreeBSD, and so forth).

Consistently use /usr/bin/env instead of /bin/bash for portability.

---

README
README.md
dns_scripts/dns_add_ionos
dns_scripts/dns_del_ionos

Two of the dns scripts have invalid shebang defines in the top of file which causes downstream breakage during rpm install. 
During build rpmbuild will add the shebangs (in this case "/usr/usr/bin/env) as a dependency and will break the install of the rpm file since '/usr/usr/bin/env' doesn't exist.  RPM normally reads shebangs and adds them to a table of dependencies.  This coding error looks to be just a typo of some sort.  The malbehavior is that:
rpm -i getssl-2.47.noarch.rpm  (install rpm)
will fail with errors because it cannot find '/usr/usr/bin/env' installed on the target system.  The error returned is "/usr/usr/bin/env" dependency not found" during install.
This bug was introduced from this commit => https://github.com/srvrco/getssl/commit/40e5084f232f424921670f36aae43ba317e41524 …

fix broken shebangs in dns_scripts and update README.md to include RPM and DEB package downloads, installation, and package building

---

getssl

Shell function get_eab_json() that generates the EAB field required in register requests when EAB is required.
Based on the array EAB_PARAMS it generates the json string EAB_JSON.
If the array has a single entry, it is treated as file path and keyid and hmac-key are read from it.
If it has two entries, they are treated as keyid string and hmac-key as base64url-encoded binary key (64 bytes).
That's how certbot for example treats their --eac-hmac-key argument.
It also requires base64url_decode which was added as well - it uses awk and might need some OS related tweaking.
For now I am using these functions in a separate script that sources getssl (--source), so it would be helpful to have them in getssl already.
I can make that separate script available as well, if it is of interest.

add EAB functions

---

getssl
test/34-ftp-passive.bats
test/34-ftp-ports.bats
test/restart-ftpd
test/run-test.cmd
test/test-config/alpine-supervisord.conf

Add support for FTP_PORT to specify a non-standard port for `ftp`, `sftp`, `ftps` or `ftpes`
Add tests for `ftps` and `ftpes`
Fixes #758

Add FTP_PORT

---

getssl

Fixes #791 bug occurring when there is no new line at the end of the ssl conf

Create newline to ensure [SAN] section can be parsed

---

common.shrc
dns_scripts/dns_add_acmedns

Hello,
A very small change (at the moment, see below) in order to improve cURL error handling. cURL isn't a good HTTP client in regard of how to catch misc errors. This PR add common pattern around error handling with cURL:
* *silent*: Disable feedback output (just leaving useful information)
* *show errors*: Still display non-HTTP related messages on stderr (e.g. invalid certificates, unresolve names, etc.)
* *temporary output*: Body is sent to a temporary file for reuse later (and still read HTTP status from stdout)
* *write output*: Let's read HTTP status
Discussion about this PR is highly open, but some interesting point that **need** to be discussed:
* Provided cURL options are passed at last for possible override. Not sure it's desirable, but that let's open for tweaks.
* …

acme-dns: improve cURL error handling

---

dns_scripts/Cloudflare-README.md

_**Important**: Someone should test and review this with an old (existing) Cloudflare account/token!_
It seems that the documentation for Cloudflare is outdated. There's no special privileges required to list zones.
What I've done:
1. Registered a new Cloudflare account.
2. Added a domain to my account. (Free Plan)
3. Created a new API token with only `DNS:Edit`.
4. Called the add/del scripts…
```bash
CF_API_TOKEN=MYSECRETTOKEN ./dns_scripts/dns_add_cloudflare test.example.net 1337
CF_API_TOKEN=MYSECRETTOKEN ./dns_scripts/dns_del_cloudflare test.example.net 1337
```
No error, the record will be created/deleted at Cloudflare without any problems.

Update Cloudflare documentation

---

dns_scripts/dns_add_linode
dns_scripts/dns_del_linode

Fixes #831
These changes update the Linode DNS scripts to use the current V4 API.
In addition, the domain matching has been corrected and improved, by searching the list of returned domains for the longest matching domain. This correctly handles situations where the domain name has more than two components (such as `domain.co.uk`), and also where a sub-domain is also stored on the same account.

Update Linode API to V4

---

README.md
getssl

Verifying PostgreSQL certificates requires setting the protocol type for s_client as it is not plain TLS, but behaving more like StartTLS in other protocols.

Allow SERVER_TYPE=postgres

---

dns_scripts/dns_add_azure

Use '--value=' instead of '-v' to allow Azure CLI to process TXT record tokens that start with special characters (in particular, a dash character). Fixes #836

Use --value= for add-record command (Issue #836)

---

dns_scripts/dns_add_hetzner
dns_scripts/dns_del_hetzner

Adds DNS challenge scripts for Hetzner DNS API.
For use the environment variable HETZNER_KEY must be set with an access token.
Also either HETZNER_ZONE_ID or HETZNER_ZONE_NAME must be set as well. When HETZNER_ZONE_ID is set it is directly used. When HETZNER_ZONE_NAME is set the zone id is obtained first.

Add Hetzner DNS scripts

---

.github/workflows/release-and-package.yml
.github/workflows/run-tests-pebble.yml
.github/workflows/run-tests-staging-acmedns.yml
.github/workflows/run-tests-staging-duckdns.yml
.github/workflows/run-tests-staging-dynu.yml
.github/workflows/shellcheck.yml
getssl
test/24-wildcard-sans.bats
test/Dockerfile-centos7
test/Dockerfile-centos7-duckdns
test/Dockerfile-centos7-dynu
test/Dockerfile-centos8
test/Dockerfile-debian
test/Dockerfile-rockylinux8
test/Dockerfile-ubuntu
test/Dockerfile-ubuntu-acmedns
test/Dockerfile-ubuntu-duckdns
test/Dockerfile-ubuntu-dynu
test/Dockerfile-ubuntu14
test/Dockerfile-ubuntu16
test/Dockerfile-ubuntu18
test/README-Testing.md
test/run-test.sh
test/u2-test-get_auth_dns-drill.bats

Try to fix test `u2` instability by retrying `drill` when it returns SERVFAIL.  Fix some warnings from Docker and Github actions at the same time.

More test fixes

---

getssl
test/u9-test-ca-newlines.bats

If the properties in /directory are not separated by newlines the URL_ variables will all contain the first URL.
To combat this this PR just adds newlines after every ",".
This fixes #765 and fixes #859.

add newlines to ca_all_loc
