getssl
=> Bugfix: $dn wasn't incremented in domain-loop

getssl
this is just the cleanup of the help message from the tabs pull-request, i aligned the texts, which i think look better
=> cleanup help-message

getssl
just to be complete, change the version to v0.14
=> up the version to v0.14

getssl
i added the DNS_EXTRA_WAIT variable to make the extra 60 seconds waiting optional and variable and found a typo for nginx
i cleaned up the config a bit as well, adding spaces for comments, making it a bit more readable
=> cleanup config-files, add DNS_EXTRA_WAIT variable, replace gninx with nginx

README.md, getssl
i setup the refetch but i was thinking maybe we should make a variable in the config for this as well, so you could set it up to always refetch the cert for some (or all) domains
=> option to refetch certificate

getssl
=> getssl#21 TEMP_DIR creation error

README.md, create-getssl-config
Add information about FTP settings to README.md and create-getssl-config files.
=> Add FTP info to config and README files

dns_scripts/dns_add_pdns-mysql, dns_scripts/dns_del_pdns-mysql
I use powerdns / mariadb (a drop-in replacement for mysql), and wanted to share my scripts.
=> Added dns_add_pdns-mysql and dns_del_pdns-mysql

getssl
Sometimes certificates are valid for many more years then 1 year.
=> Better force_renew

dns_scripts/dns_add_dnspod, dns_scripts/dns_del_dnspod
Add Dnspod script
Dnspod provides domain name services in China.
=> Add Dnspod script

getssl
I'm not quite sure if that is clean and sufficient, so I'm curious for any improvements. (Issue #121)
=> removed IPv6 switch in favour of checking both IPv4 and IPv6

getssl
Note to self: read the CONTRIBUTING.md next time :)
=> Add and comment optional sshuserid for ssh ACL

getssl
Tidied up the tmpfile handling for the upgrade process a bit as discussed in #206.
=> tidied up upgrade tmpfile handling (1.95)

LICENSE
This fixes #219 by replacing the LICENSE file with the proper GPL**3** license file.
=> Provide GPLv3 rather than GPLv2

dns_scripts/DNS_ROUTE53.md, dns_scripts/dns_route53.py
I needed to be able to to DNS-01 from AWS on instances that don't have direct internet access.
This works rather well.
=> Adding the Route53 dns script and some docs.

dns_scripts/dns_add_nsupdate, dns_scripts/dns_del_nsupdate
Streamlined the pipeline for nsupdate, obviating the need for a temp file
=> Nsupdate one-liner

getssl
| Q | A
| --- | ---
| Bug fix? | a bit
| New feature? | enhancement
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #381 
| Related issues/PRs | #302, #382
=>  Allow dns checks to deal with CNAME records 

README.md, dns_scripts/GoDaddy-README.txt, dns_scripts/dns_add_godaddy, dns_scripts/dns_add_joker, dns_scripts/dns_add_nsupdate, dns_scripts/dns_add_ovh, dns_scripts/dns_del_godaddy, dns_scripts/dns_del_joker, dns_scripts/dns_del_nsupdate, dns_scripts/dns_del_ovh, dns_scripts/dns_godaddy, getssl
Rebases APIv2 onto master and fixes conflicts.
Also fixes #374
**Known issue: ** First run for a domain causes "json was blank" error. Just run `getssl DOMAIN_HERE` again and it'll work fine.
**IMPORTANT: remove your previous certificate signing requests before running, ACMEv1 CSRs will not play nicely with ACMEv2**
=> Applied ACMEv2

getssl
Add User-Agent to all requests
=> Add User-Agent header (fixes #453)

getssl
This will fix all shellcheck issues (or disable shellcheck if it's ok to ignore them)
=> fix shellcheck issues

getssl
Fix for #475 and #483 - update grep regex for >9 subdomains in json_get
=> Fix more than 10 domains

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, README.md, test/README.md
This PR will lint all the `.md` files.
See <https://github.com/igorshubovych/markdownlint-cli> for more information.
=> markdownlint

dns_scripts/dns_add_clouddns, dns_scripts/dns_del_clouddns, getssl
Hello,
this PR adds support for DNS ACME challenges using CloudDNS API by VSHosting (https://github.com/vshosting/clouddns). It is based on the CloudFlare DNS plugin.
Let me know if there are any issues to be resolved prior to merge.
=> Add support for CloudDNS

test/1-simple-http01.bats, test/2-simple-dns01.bats, test/4-more-than-10-hosts.bats, test/Dockerfile-ubuntu18, test/README.md, test/debug-test.sh, test/run-all-tests.sh
Check output for "Error", "Failed" and "Warning"
=> Improve tests

docker-compose.yml, getssl, test/Dockerfile-alpine, test/Dockerfile-centos6, test/Dockerfile-ubuntu18, test/Dockerfile-ubuntu18-no-gawk, test/alpine-supervisord.conf, test/restart-nginx, test/test-config/getssl-dns01.cfg, test/test-config/getssl-http01-10-hosts.cfg, test/test-config/getssl-http01.cfg, test/test_helper.bash
bugs found while testing using Alpine linux
=> Fix epoch_date for busybox and json_awk for gawk v5

getssl
Update the templates to include a SSH_OPTS example and some more comments.
=> Add SSH_OPTS to template

getssl, test/3-dual-rsa-ecdsa.bats, test/5-secp384-http01.bats, test/Dockerfile-debian, test/README.md, test/test-config/getssl-dns01-dual-rsa-ecdsa.cfg, test/test-config/getssl-http01-dual-rsa-ecdsa.cfg, test/test-config/getssl-http01-secp384.cfg, test/test-config/getssl-http01-secp521.cfg
2020-02-12 Fix for DUAL_RSA_ECDSA not working with ACMEv2 (#334, #474, #502)
2020-02-12 Fix #424 - Sporadic "error in EC signing couldn't get R from ..."
and added tests for both of the above fixes
=> Fixes for DUAL_RSA_ECDSA and ecliptic curve problems

getssl
=> Fix "Registration key already in use" error

dns_scripts/dns_add_nsupdate, dns_scripts/dns_del_nsupdate
```
$ nsupdate "-k ./acme.key"               
could not read key from  ./acme.{private,key}: file not found
```
has it even been tested?
=> ${options} must be without quotes

dns_scripts/dns_add_nsupdate, dns_scripts/dns_del_nsupdate
add support for custom server and zone
=> Nsupdate options

dns_scripts/dns_add_duckdns, dns_scripts/dns_add_nsupdate, dns_scripts/dns_del_duckdns, dns_scripts/dns_del_nsupdate, docker-compose.yml, getssl, test/2-simple-dns01.bats, test/3-dual-rsa-ecdsa.bats, test/4-more-than-10-hosts.bats, test/5-secp384-http01.bats, test/6-dual-rsa-ecdsa-copy-2-locations.bats, test/7-duckdns-dns01.bats, test/8-duckdns-ecdsa.bats, test/debug-test.sh, test/run-all-tests.cmd, test/run-all-tests.sh, test/test-config/getssl-duckdns01.cfg
=> Sign string using asn1parse

getssl
vim directives to highlight cfg files as shell ones
=> add vim lines for cfg files

.github/workflows/stale.yml
Any issue labelled with "needs more information" and not updated after 90 days will be auto-closed
=> Add a gitaction to close stale issues

.github/workflows/run-all-tests.yml, dns_scripts/dns_add_challtestsrv, getssl, test/2-simple-dns01-nslookup.bats, test/7-duckdns-dns01-dig.bats, test/7-duckdns-dns01-nslookup.bats, test/8-duckdns-ecdsa.bats, test/9-multiple-domains-dns01.bats, test/Dockerfile-centos7, test/debug-test.sh, test/test-config/getssl-dns01-dual-rsa-ecdsa.cfg, test/test-config/getssl-dns01.cfg, test/test-config/getssl-duckdns01.cfg, test/test-config/getssl-ignore-directory-domain.cfg, test/test-config/getssl-multiple-domains-dns01.cfg, test/test_helper.bash
2020-02-22 Change sign_string to use openssl asn1parse (better fix for #424)
2020-02-23 Add dig to config check for systems without drill (ubuntu)
2020-03-11 Use dig +trace to find primary name server and improve dig parsing of CNAME
2020-03-12 Fix bug with DNS validation and multiple domains (#524)
2020-03-24 Find primary ns using all dns utils (dig, host, nslookup) (2.21)
=> Pre-release 2.21

getssl
Look at issue #552, should be an easy fix
=> Fixed ipv4 confirmation with nslookup

getssl
Fixes #432 which I encountered when renewing my own domains
=> Fix ftp/sftp problems if challenge starts with a dash

dns_scripts/dns_route53.py
tested on FreeBSD 11.3-RELEASE-p6 with python 3.6.9
=> Fix route53 script for python 3.

getssl, test/3-dual-rsa-ecdsa.bats, test/test_helper.bash
=> Fix missing fullchain.ec.crt when creating dual certificates

getssl, test/13-notify-valid.bats, test/14-test-revoke.bats
Fixes --revoke (#558)
Adds --notify-valid (#559)
=> Fix --revoke

getssl, test/15-test-revoke-no-suffix.bats, test/test-config/getssl-http01-no-suffix.cfg, test/test-config/getssl-staging-dns01-no-suffix.cfg
=> Fix revoke when no CA suffix is specified

getssl, test/14-test-revoke.bats, test/15-test-revoke-no-suffix.bats, test/6-dual-rsa-ecdsa-copy-2-locations.bats, test/test-config/getssl-http01-dual-rsa-ecdsa-2-locations-wrong-nginx.cfg, test/test-config/getssl-http01-dual-rsa-ecdsa-old-nginx.cfg, test/test-config/nginx-ubuntu-dual-certs, test/test_helper.bash
Fix problem checking remote certificate with duals certs and tls1.3 (#570)
=> Change to use -sigalgs

getssl, test/17-test-spaces-in-sans-dns01.bats, test/17-test-spaces-in-sans-http01.bats, test/test-config/getssl-dns01-spaces-and-commas-sans.cfg, test/test-config/getssl-http01-spaces-and-commas-sans.cfg, test/test-config/getssl-staging-dns01-no-suffix.cfg, test/test-config/getssl-staging-dns01.cfg
=> Fixes problems with SANS separated by spaces and commas

README.md
Please see the rich diff for the visual difference :D
=> Improve README.md code block readability by correct syntax highlight

getssl, test/29-check-mktemp-failure.bats, test/u3-mktemp-template.bats
=> mktemp not working correctly on Alpine Linux (added XXXXXX to template)

getssl, test/30-handle-dig-failure.bats
=> Handle dig failure

.github/workflows/run-tests-pebble.yml, test/Dockerfile-bash4-0, test/Dockerfile-bash4-2, test/Dockerfile-bash5-0, test/Dockerfile-centos6, test/run-test.cmd, test/run-test.sh
=> Add tests for bash 4.0, 4.2, 5.0

getssl, test/15-test-revoke-no-suffix.bats
=> Use -r option for dig to force default dig output

getssl
=> Check for Valid ACME response and continue waiting

README.md, getssl, test/32-test-upgrade.bats
Implemented functionality and corresponding usage-text of issue 634 (feature request to allow upgrading without domain).
=> Implement #634 - allow -u without domain(s)

getssl
=> Prevent listing the complete file if version tag missing

getssl
Moin, moin Folks,
I had issues with the uploads of the challenges because my provider need ftp with SSL. I add the few necessary lines. My be it helps
Regards and thanks for your work so far
MIscha
=> ftp with explicit SSL

README.md, getssl
If the certificate on the webserver doesn't match the domain then print both in the warning message
=> Better message for cert does not match

dns_scripts/dns_add_del_aliyun.sh
Founded in 2009, Aliyun is a leading cloud computing and artificial intelligence technology company in China
=> Create Aliyun DNS Scripts

test/Dockerfile-alpine, test/Dockerfile-centos6, test/Dockerfile-centos7, test/Dockerfile-centos7-staging, test/Dockerfile-centos8, test/Dockerfile-debian, test/Dockerfile-ubuntu, test/Dockerfile-ubuntu-staging, test/Dockerfile-ubuntu16, test/Dockerfile-ubuntu18
This will make the test process faster!
=> Improve test process(mostly the Dockerfile)

dns_scripts/dns_route53.py
Fixed issue with deprecated function query for dns.resolver.Resolver
=> DeprecationWarning: please use dns.resolver.Resolver.resolve()

getssl, test/19-test-add-to-sans.bats
=> Remove spaces and sort when checking if SANS list changed

dns_scripts/dns_add_ovh, dns_scripts/dns_del_ovh
Support environment variables when using DNS challenges with OVH
=> [DNS-01][OVH] Config from env

.github/workflows/stale2.yml, getssl, test/2-simple-dns01-dig.bats
=> release-2.37

getssl, test/37-idn.bats, test/38-idn-http01-check-noidnout.bats, test/run-test.cmd, test/run-test.sh, test/test_helper.bash
Fixes #682 (bug with last release: host/nslookup called with +noidnout which generates an error)
=> Fix host idn bug

getssl, test/0-test-curl-error.bats, test/32-test-upgrade.bats, test/39-private-key-alg-changed.bats
Add a test for the 'delete key file if the key algorithm changes` in pr #706 from @makuhama 
Fix #276 by recreating the certificate if the key algorithm is changed
=> Tests for pr706 and fix276

dns_scripts/DNS_IONOS.md, dns_scripts/dns_add_ionos, dns_scripts/dns_del_ionos
Tested and working for me. Please check if the coding style is ok for you.
=> add scripts to use IONOS DNS API

getssl
fixes #701 
please check whether the code matches your expectations and give me feedback how to improve.
=> detect Solaris derivates and add /usr/gnu/bin to PATH

README.md, dns_scripts/dns_add_ispconfig, dns_scripts/dns_del_ispconfig, dns_scripts/ispconfig_soap.php, getssl
Added support to add and delete DNS records in ISPConfig
=> Supporting ISPConfig API

.github/workflows/run-tests-staging-acmedns.yml, .github/workflows/run-tests-staging-duckdns.yml, .github/workflows/run-tests-staging-dynu.yml, getssl, test/34-ftp-passive.bats, test/Dockerfile-centos8
Latest ubuntu breaks some of the tests
=> Fix ubuntu tests

dns_scripts/dns_add_hostway, dns_scripts/dns_del_hostway
Added support to add and delete DNS records for Hostways API
=> Added support for Hostway API

getssl, test/34-ftp-passive.bats
Add support for FTP_ARGS to ftp/lftp (but not ftps/ftpes)
=> Add FTP_ARGS for ftp/lftp

getssl
Bad FULL_CHAIN_INCLUDE_ROOT value compare
=> FULL_CHAIN_INCLUDE_ROOT compare bugfix

dns_scripts/dns_add_vultr, dns_scripts/dns_del_vultr
Again, exactly what it says on the tin :)
=> Use /usr/bin/env instead of hardcoding bash path.

dns_scripts/dns_add_dnsmasq, dns_scripts/dns_del_dnsmasq
I did run a prof of concept if and how dnsmasq could be used for wildcard certification challange. Yes it is possible. This is the getssl-part of this environment. Thanks a lot for getssl - I like it very much.
=> dns_add and dns_del for dnsmasq - a lightweight DHCP and caching DNS server

dns_scripts/GoDaddy-README.txt
=> Update GoDaddy README
